// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action EditAction;
    
    private Gtk.Action HelpAction;
    
    private Gtk.Action QuitAction;
    
    private Gtk.Action AboutAction;
    
    private Gtk.Action PreferencesAction;
    
    private Gtk.VBox mainBox;
    
    private Gtk.MenuBar menuBar;
    
    private Gtk.VBox mainSearchBox;
    
    private Gtk.VBox searchBox;
    
    private Gtk.HBox searchEntryBox;
    
    private Gtk.Entry searchEntry;
    
    private Gtk.ComboBox searchTypeComboBox;
    
    private Gtk.Expander advancedSearchExpander;
    
    private Gtk.VBox advancedSearchBox;
    
    private Gtk.HBox phraseSearchBox;
    
    private Gtk.Label phraseSearchLabel;
    
    private Gtk.Entry phraseSearchEntry;
    
    private Gtk.HBox excludeSearchBox;
    
    private Gtk.Label excludeSearchLabel;
    
    private Gtk.Entry excludeSearchEntry;
    
    private Gtk.HBox hbox5;
    
    private Gtk.Label advancedSearchLabel;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.TextView resultsView;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("_File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, "<Alt><Mod2>f");
        this.EditAction = new Gtk.Action("EditAction", Mono.Unix.Catalog.GetString("_Edit"), null, null);
        this.EditAction.ShortLabel = Mono.Unix.Catalog.GetString("Edit");
        w1.Add(this.EditAction, null);
        this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("_Help"), null, null);
        this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction, null);
        this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "Quit");
        this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w1.Add(this.QuitAction, "<Control><Mod2>q");
        this.AboutAction = new Gtk.Action("AboutAction", Mono.Unix.Catalog.GetString("About"), null, "About");
        this.AboutAction.ShortLabel = Mono.Unix.Catalog.GetString("About");
        w1.Add(this.AboutAction, null);
        this.PreferencesAction = new Gtk.Action("PreferencesAction", Mono.Unix.Catalog.GetString("_Preferences"), null, "Preferences");
        this.PreferencesAction.ShortLabel = Mono.Unix.Catalog.GetString("_Preferences");
        w1.Add(this.PreferencesAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Monogle");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-find", Gtk.IconSize.Menu, 16);
        this.WindowPosition = ((Gtk.WindowPosition)(1));
        this.DefaultWidth = 800;
        this.DefaultHeight = 600;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.mainBox = new Gtk.VBox();
        this.mainBox.Name = "mainBox";
        this.mainBox.Spacing = 6;
        this.mainBox.BorderWidth = ((uint)(1));
        // Container child mainBox.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menuBar'><menu name='FileAction' action='FileAction'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='PreferencesAction' action='PreferencesAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
        this.menuBar = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menuBar")));
        this.menuBar.Name = "menuBar";
        this.mainBox.Add(this.menuBar);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.mainBox[this.menuBar]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child mainBox.Gtk.Box+BoxChild
        this.mainSearchBox = new Gtk.VBox();
        this.mainSearchBox.Name = "mainSearchBox";
        this.mainSearchBox.Spacing = 6;
        this.mainSearchBox.BorderWidth = ((uint)(1));
        // Container child mainSearchBox.Gtk.Box+BoxChild
        this.searchBox = new Gtk.VBox();
        this.searchBox.Name = "searchBox";
        this.searchBox.Spacing = 6;
        this.searchBox.BorderWidth = ((uint)(2));
        // Container child searchBox.Gtk.Box+BoxChild
        this.searchEntryBox = new Gtk.HBox();
        this.searchEntryBox.Name = "searchEntryBox";
        this.searchEntryBox.Spacing = 6;
        this.searchEntryBox.BorderWidth = ((uint)(1));
        // Container child searchEntryBox.Gtk.Box+BoxChild
        this.searchEntry = new Gtk.Entry();
        this.searchEntry.TooltipMarkup = "Enter your search terms here";
        this.searchEntry.CanFocus = true;
        this.searchEntry.Name = "searchEntry";
        this.searchEntry.IsEditable = true;
        this.searchEntry.InvisibleChar = '●';
        this.searchEntryBox.Add(this.searchEntry);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.searchEntryBox[this.searchEntry]));
        w3.Position = 0;
        // Container child searchEntryBox.Gtk.Box+BoxChild
        this.searchTypeComboBox = Gtk.ComboBox.NewText();
        this.searchTypeComboBox.AppendText(Mono.Unix.Catalog.GetString("Web"));
        this.searchTypeComboBox.AppendText(Mono.Unix.Catalog.GetString("Image"));
        this.searchTypeComboBox.AppendText(Mono.Unix.Catalog.GetString("Blog"));
        this.searchTypeComboBox.AppendText(Mono.Unix.Catalog.GetString("News"));
        this.searchTypeComboBox.CanDefault = true;
        this.searchTypeComboBox.Name = "searchTypeComboBox";
        this.searchTypeComboBox.Active = 0;
        this.searchEntryBox.Add(this.searchTypeComboBox);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.searchEntryBox[this.searchTypeComboBox]));
        w4.Position = 1;
        w4.Expand = false;
        w4.Fill = false;
        this.searchBox.Add(this.searchEntryBox);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.searchBox[this.searchEntryBox]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        // Container child searchBox.Gtk.Box+BoxChild
        this.advancedSearchExpander = new Gtk.Expander(null);
        this.advancedSearchExpander.CanFocus = true;
        this.advancedSearchExpander.Name = "advancedSearchExpander";
        this.advancedSearchExpander.BorderWidth = ((uint)(1));
        // Container child advancedSearchExpander.Gtk.Container+ContainerChild
        this.advancedSearchBox = new Gtk.VBox();
        this.advancedSearchBox.Name = "advancedSearchBox";
        this.advancedSearchBox.Spacing = 6;
        this.advancedSearchBox.BorderWidth = ((uint)(5));
        // Container child advancedSearchBox.Gtk.Box+BoxChild
        this.phraseSearchBox = new Gtk.HBox();
        this.phraseSearchBox.Name = "phraseSearchBox";
        this.phraseSearchBox.Spacing = 6;
        this.phraseSearchBox.BorderWidth = ((uint)(2));
        // Container child phraseSearchBox.Gtk.Box+BoxChild
        this.phraseSearchLabel = new Gtk.Label();
        this.phraseSearchLabel.Name = "phraseSearchLabel";
        this.phraseSearchLabel.LabelProp = Mono.Unix.Catalog.GetString("Entire Phrase:");
        this.phraseSearchBox.Add(this.phraseSearchLabel);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.phraseSearchBox[this.phraseSearchLabel]));
        w6.Position = 0;
        w6.Expand = false;
        w6.Fill = false;
        // Container child phraseSearchBox.Gtk.Box+BoxChild
        this.phraseSearchEntry = new Gtk.Entry();
        this.phraseSearchEntry.TooltipMarkup = "Find web pages that have this exact wording or phrase";
        this.phraseSearchEntry.CanFocus = true;
        this.phraseSearchEntry.Name = "phraseSearchEntry";
        this.phraseSearchEntry.IsEditable = true;
        this.phraseSearchEntry.InvisibleChar = '●';
        this.phraseSearchBox.Add(this.phraseSearchEntry);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.phraseSearchBox[this.phraseSearchEntry]));
        w7.Position = 1;
        this.advancedSearchBox.Add(this.phraseSearchBox);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.advancedSearchBox[this.phraseSearchBox]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        // Container child advancedSearchBox.Gtk.Box+BoxChild
        this.excludeSearchBox = new Gtk.HBox();
        this.excludeSearchBox.Name = "excludeSearchBox";
        this.excludeSearchBox.Spacing = 6;
        this.excludeSearchBox.BorderWidth = ((uint)(2));
        // Container child excludeSearchBox.Gtk.Box+BoxChild
        this.excludeSearchLabel = new Gtk.Label();
        this.excludeSearchLabel.Name = "excludeSearchLabel";
        this.excludeSearchLabel.LabelProp = Mono.Unix.Catalog.GetString("Not those words:");
        this.excludeSearchBox.Add(this.excludeSearchLabel);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.excludeSearchBox[this.excludeSearchLabel]));
        w9.Position = 0;
        w9.Expand = false;
        w9.Fill = false;
        // Container child excludeSearchBox.Gtk.Box+BoxChild
        this.excludeSearchEntry = new Gtk.Entry();
        this.excludeSearchEntry.TooltipMarkup = "Don't show pages that have any of these unwanted words";
        this.excludeSearchEntry.CanFocus = true;
        this.excludeSearchEntry.Name = "excludeSearchEntry";
        this.excludeSearchEntry.IsEditable = true;
        this.excludeSearchEntry.InvisibleChar = '●';
        this.excludeSearchBox.Add(this.excludeSearchEntry);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.excludeSearchBox[this.excludeSearchEntry]));
        w10.Position = 1;
        this.advancedSearchBox.Add(this.excludeSearchBox);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.advancedSearchBox[this.excludeSearchBox]));
        w11.Position = 1;
        w11.Expand = false;
        w11.Fill = false;
        // Container child advancedSearchBox.Gtk.Box+BoxChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        this.advancedSearchBox.Add(this.hbox5);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.advancedSearchBox[this.hbox5]));
        w12.Position = 2;
        this.advancedSearchExpander.Add(this.advancedSearchBox);
        this.advancedSearchLabel = new Gtk.Label();
        this.advancedSearchLabel.Name = "advancedSearchLabel";
        this.advancedSearchLabel.LabelProp = Mono.Unix.Catalog.GetString("Advanced Search");
        this.advancedSearchLabel.UseUnderline = true;
        this.advancedSearchExpander.LabelWidget = this.advancedSearchLabel;
        this.searchBox.Add(this.advancedSearchExpander);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.searchBox[this.advancedSearchExpander]));
        w14.Position = 1;
        this.mainSearchBox.Add(this.searchBox);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.mainSearchBox[this.searchBox]));
        w15.Position = 0;
        w15.Expand = false;
        // Container child mainSearchBox.Gtk.Box+BoxChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.HscrollbarPolicy = ((Gtk.PolicyType)(2));
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.resultsView = new Gtk.TextView();
        this.resultsView.CanFocus = true;
        this.resultsView.Name = "resultsView";
        this.resultsView.Editable = false;
        this.resultsView.CursorVisible = false;
        this.resultsView.WrapMode = ((Gtk.WrapMode)(2));
        this.GtkScrolledWindow.Add(this.resultsView);
        this.mainSearchBox.Add(this.GtkScrolledWindow);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.mainSearchBox[this.GtkScrolledWindow]));
        w17.Position = 1;
        this.mainBox.Add(this.mainSearchBox);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.mainBox[this.mainSearchBox]));
        w18.Position = 1;
        this.Add(this.mainBox);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.searchTypeComboBox.HasDefault = true;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.QuitAction.Activated += new System.EventHandler(this.OnQuit);
        this.AboutAction.Activated += new System.EventHandler(this.OnAbout);
        this.PreferencesAction.Activated += new System.EventHandler(this.OnPreferences);
        this.searchEntry.Activated += new System.EventHandler(this.OnSearch);
        this.phraseSearchEntry.Activated += new System.EventHandler(this.OnSearch);
        this.excludeSearchEntry.Activated += new System.EventHandler(this.OnSearch);
    }
}
