// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action EditAction;
    
    private Gtk.Action HelpAction;
    
    private Gtk.Action QuitAction;
    
    private Gtk.Action AboutAction;
    
    private Gtk.Action PreferencesAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menuBar;
    
    private Gtk.VBox vbox4;
    
    private Gtk.VBox vbox5;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Entry searchEntry;
    
    private Gtk.ComboBox searchTypeComboBox;
    
    private Gtk.Expander advancedSearchExpander;
    
    private Gtk.Label advancedSearchLabel;
    
    private Gtk.DrawingArea drawingArea;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("_File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, "<Alt><Mod2>f");
        this.EditAction = new Gtk.Action("EditAction", Mono.Unix.Catalog.GetString("_Edit"), null, null);
        this.EditAction.ShortLabel = Mono.Unix.Catalog.GetString("Edit");
        w1.Add(this.EditAction, null);
        this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("_Help"), null, null);
        this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction, null);
        this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "Quit");
        this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w1.Add(this.QuitAction, "<Control><Mod2>q");
        this.AboutAction = new Gtk.Action("AboutAction", Mono.Unix.Catalog.GetString("About"), null, "About");
        this.AboutAction.ShortLabel = Mono.Unix.Catalog.GetString("About");
        w1.Add(this.AboutAction, null);
        this.PreferencesAction = new Gtk.Action("PreferencesAction", Mono.Unix.Catalog.GetString("_Preferences"), null, "Preferences");
        this.PreferencesAction.ShortLabel = Mono.Unix.Catalog.GetString("_Preferences");
        w1.Add(this.PreferencesAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Monogle");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-find", Gtk.IconSize.Menu, 16);
        this.WindowPosition = ((Gtk.WindowPosition)(1));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menuBar'><menu name='FileAction' action='FileAction'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='PreferencesAction' action='PreferencesAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
        this.menuBar = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menuBar")));
        this.menuBar.Name = "menuBar";
        this.vbox1.Add(this.menuBar);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menuBar]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.vbox4 = new Gtk.VBox();
        this.vbox4.Name = "vbox4";
        this.vbox4.Spacing = 6;
        // Container child vbox4.Gtk.Box+BoxChild
        this.vbox5 = new Gtk.VBox();
        this.vbox5.Name = "vbox5";
        this.vbox5.Spacing = 6;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.searchEntry = new Gtk.Entry();
        this.searchEntry.CanFocus = true;
        this.searchEntry.Name = "searchEntry";
        this.searchEntry.IsEditable = true;
        this.searchEntry.InvisibleChar = '●';
        this.hbox2.Add(this.searchEntry);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox2[this.searchEntry]));
        w3.Position = 0;
        // Container child hbox2.Gtk.Box+BoxChild
        this.searchTypeComboBox = Gtk.ComboBox.NewText();
        this.searchTypeComboBox.AppendText(Mono.Unix.Catalog.GetString("Web"));
        this.searchTypeComboBox.AppendText(Mono.Unix.Catalog.GetString("Image"));
        this.searchTypeComboBox.AppendText(Mono.Unix.Catalog.GetString("Blog"));
        this.searchTypeComboBox.AppendText(Mono.Unix.Catalog.GetString("News"));
        this.searchTypeComboBox.CanDefault = true;
        this.searchTypeComboBox.Name = "searchTypeComboBox";
        this.searchTypeComboBox.Active = 0;
        this.hbox2.Add(this.searchTypeComboBox);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.searchTypeComboBox]));
        w4.Position = 1;
        w4.Expand = false;
        w4.Fill = false;
        this.vbox5.Add(this.hbox2);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        // Container child vbox5.Gtk.Box+BoxChild
        this.advancedSearchExpander = new Gtk.Expander(null);
        this.advancedSearchExpander.CanFocus = true;
        this.advancedSearchExpander.Name = "advancedSearchExpander";
        this.advancedSearchLabel = new Gtk.Label();
        this.advancedSearchLabel.Name = "advancedSearchLabel";
        this.advancedSearchLabel.LabelProp = Mono.Unix.Catalog.GetString("Advanced");
        this.advancedSearchLabel.UseUnderline = true;
        this.advancedSearchExpander.LabelWidget = this.advancedSearchLabel;
        this.vbox5.Add(this.advancedSearchExpander);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox5[this.advancedSearchExpander]));
        w6.Position = 1;
        this.vbox4.Add(this.vbox5);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox4[this.vbox5]));
        w7.Position = 0;
        w7.Expand = false;
        // Container child vbox4.Gtk.Box+BoxChild
        this.drawingArea = new Gtk.DrawingArea();
        this.drawingArea.Name = "drawingArea";
        this.vbox4.Add(this.drawingArea);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox4[this.drawingArea]));
        w8.Position = 1;
        this.vbox1.Add(this.vbox4);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
        w9.Position = 1;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 633;
        this.DefaultHeight = 448;
        this.searchTypeComboBox.HasDefault = true;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.QuitAction.Activated += new System.EventHandler(this.OnQuit);
        this.AboutAction.Activated += new System.EventHandler(this.OnAbout);
    }
}
